score                   = <comment*> 
                          not-a-comment+ (<comment+> not-a-comment+)* 
                           <comment*>
<not-a-comment>	        = !comment #".|\n|\r"
comment                 = long-comment | short-comment | barline
long-comment            = "###" inside-long-comment* "###"
inside-long-comment     = !"###" #".|\n|\r" | long-comment
short-comment           = "#" #".*" #"(\n|\r|$)+"
barline                 = "|"