duration                = (note-length | seconds | milliseconds)
                          (<ows> barline? <ows> subduration)*
                          (barline? <ows> slur)?
<subduration>           = tie <ows> barline? <ows>
                          (note-length | seconds | milliseconds) <ows>

seconds                 = positive-number <"s">
milliseconds            = positive-number <"ms">

note-length             = positive-number dots?
dots                    = #"\.+"
<tie>                   = <"~">
slur                    = <"~">
