score             = <ows> header? part*
header            = !calls <ows> music-data+
part              = calls <ows> music-data*
calls             = name
                    (<ows> <"/"> <ows> name)*
                    (<ows> nickname)?
                    <ows> <":">
<music-data>      = !part #".|\n|\r"

