blank_issues_enabled: false
contact_links:
  - name: Alda documentation
    url: https://github.com/alda-lang/alda/blob/master/doc/index.md
    about: Have you checked the docs?
  - name: Alda Slack group
    url: http://slack.alda.io
    about: Need help? Come chat with us on Slack!
