    (* inline clojure expressions *)

clj-character           = <"\\"> ( "newline" / "space" / "tab" /
                                   "formfeed" / "backspace" / "return" /
                                   #"(o|u)\d{4}" / #"." )

clj-string              = <"\""> inside-clj-string* <"\"">
<inside-clj-string>     = !"\"" #".|\n|\r" | "\\\""

clj-expr                = <"("> inside-clj-expr* <")">
<inside-clj-expr>       = !( "(" | ")" | "\"" | "\\" )
                          #".|\n|\r" | clj-string | clj-character | clj-expr

